### ISSUE TITLE
[HomeApplication] Allow click items in edit mode.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#21]
When edit mode is activated, item's Clicked events are not raised.

**Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by huiyueun** [comment]
Fixed.
https://github.com/dalihub/nui-demo/commit/288aaa5b1a017dc7273db5fde22ce2b82ad69527

**Comment by p-czaja** [comment]
Dear @huiyueun,
I tested your fix and it still doesnt't work.

**Comment by huiyueun** [comment]
Please check. I've fixed
https://github.com/dalihub/nui-demo/commit/e46d8ff9af62fc5f07afce008f25282a10c0741b
