### ISSUE TITLE
[HomeApplication][WApps] For Items added in edit mode 'minus' icon is not clickable.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#71]
1. Modified sample that shows the issue can be found [here](https://github.com/p-czaja/nui-demo/tree/addedItemNotClicable). 
2. Steps to reproduce:
    - enable edit mode
    - delete one of the items
    - new item based on removed one will be added by `AppendItem()`.
    - try click minus icon once again.
3. Tested on:
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200605.2;
Release=20200605.2;
[Build]
Type=eng;
Date=20200605_215033;
Time=21:50:33;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
@huiyueun could you please take a look?

**Comment by huiyueun** [comment]
I think it is fixed by this patch -> https://github.com/dalihub/nui-demo/pull/68
could you check this?

**Comment by p-czaja** [comment]
Unfortunatelly this issue still exists. Please find example rebased after your changes [here](https://github.com/p-czaja/nui-demo/tree/addedItemNotClicable).

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/81
